services:
    application:
        build:
            context: "./docker/develop"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP:-1000}"
                NODE_VERSION: "${APP_NODE_VERSION:-20}"
        image: "${COMPOSE_PROJECT_NAME:-template}-dev-app"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            MYSQL_HOST: "${DB_HOST}"
            TZ: "${APP_TIMEZONE:-America/Recife}"
            WWWUSER: "${WWWUSER:-1000}"
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
        volumes:
            - ".:/var/www/html"
        networks:
            - template
        depends_on:
            - mysql
            - redis
            - minio
            - soketi

    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - "template-mysql:/var/lib/mysql"
        command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
        networks:
            - template

    redis:
        image: "redis:alpine"
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - "template-redis:/data"
        networks:
            - template

    minio:
        image: "minio/minio:latest"
        ports:
            - "${FORWARD_MINIO_PORT:-9000}:9000"
            - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
        environment:
            MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID:-template}"
            MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY:-template}"
        volumes:
            - "template-minio:/data/minio"
        networks:
            - template
        command: 'minio server /data/minio --console-address ":8900"'

    soketi:
        image: "quay.io/soketi/soketi:latest-16-alpine"
        environment:
            SOKETI_DEBUG: "${SOKETI_DEBUG:-1}"
            SOKETI_METRICS_SERVER_PORT: "9601"
            SOKETI_DEFAULT_APP_ID: "${PUSHER_APP_ID}"
            SOKETI_DEFAULT_APP_KEY: "${PUSHER_APP_KEY}"
            SOKETI_DEFAULT_APP_SECRET: "${PUSHER_APP_SECRET}"
        ports:
            - "${PUSHER_PORT:-6001}:6001"
            - "${PUSHER_METRICS_PORT:-9601}:9601"
        networks:
            - template

networks:
    template:
        driver: bridge
volumes:
    template-mysql:
        driver: local
    template-redis:
        driver: local
    template-minio:
        driver: local
